services:
  app:
    image: dartw/mercury:latest
    container_name: chemindex-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.development.local
    depends_on:
      - mongo
    networks:
      - chem-network

  mongo:
    image: mongo:6
    container_name: chemindex-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - chem-network

volumes:
  mongodb_data:

networks:
  chem-network:
    driver: bridge
